In [1]:
#importing libraries
import os
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Construct the absolute file path to your dataset
file_path = os.path.join(os.path.expanduser("~"), "Desktop", "flatiorn", "project2", "kc_house_data.csv")

# Read the CSV file and store it as a DataFrame
df = pd.read_csv(file_path)

# Review first 5 data 
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,greenbelt,...,sewer_system,sqft_above,sqft_basement,sqft_garage,sqft_patio,yr_built,yr_renovated,address,lat,long
0,7399300360,5/24/2022,675000.0,4,1.0,1180,7140,1.0,NO,NO,...,PUBLIC,1180,0,0,40,1969,0,"2102 Southeast 21st Court, Renton, Washington ...",47.461975,-122.19052
1,8910500230,12/13/2021,920000.0,5,2.5,2770,6703,1.0,NO,NO,...,PUBLIC,1570,1570,0,240,1950,0,"11231 Greenwood Avenue North, Seattle, Washing...",47.711525,-122.35591
2,1180000275,9/29/2021,311000.0,6,2.0,2880,6156,1.0,NO,NO,...,PUBLIC,1580,1580,0,0,1956,0,"8504 South 113th Street, Seattle, Washington 9...",47.502045,-122.22520
3,1604601802,12/14/2021,775000.0,3,3.0,2160,1400,2.0,NO,NO,...,PUBLIC,1090,1070,200,270,2010,0,"4079 Letitia Avenue South, Seattle, Washington...",47.566110,-122.29020
4,8562780790,8/24/2021,592500.0,2,2.0,1120,758,2.0,NO,NO,...,PUBLIC,1120,550,550,30,2012,0,"2193 Northwest Talus Drive, Issaquah, Washingt...",47.532470,-122.07188

In [3]:
#descriptive statistics
df.describe()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,sqft_above,sqft_basement,sqft_garage,sqft_patio,yr_built,yr_renovated,lat,long
count,3.015500e+04,3.015500e+04,30155.000000,30155.000000,30155.000000,3.015500e+04,30155.000000,30155.000000,30155.000000,30155.000000,30155.000000,30155.000000,30155.000000,30155.000000,30155.000000
mean,4.538104e+09,1.108536e+06,3.413530,2.334737,2112.424739,1.672360e+04,1.543492,1809.826098,476.039396,330.211142,217.412038,1975.163953,90.922301,47.328076,-121.317397
std,2.882587e+09,8.963857e+05,0.981612,0.889556,974.044318,6.038260e+04,0.567717,878.306131,579.631302,285.770536,245.302792,32.067362,416.473038,1.434005,5.725475
min,1.000055e+06,2.736000e+04,0.000000,0.000000,3.000000,4.020000e+02,1.000000,2.000000,0.000000,0.000000,0.000000,1900.000000,0.000000,21.274240,-157.791480
25%,2.064175e+09,6.480000e+05,3.000000,2.000000,1420.000000,4.850000e+03,1.000000,1180.000000,0.000000,0.000000,40.000000,1953.000000,0.000000,47.405320,-122.326045
50%,3.874011e+09,8.600000e+05,3.000000,2.500000,1920.000000,7.480000e+03,1.500000,1560.000000,0.000000,400.000000,150.000000,1977.000000,0.000000,47.551380,-122.225585
75%,7.287100e+09,1.300000e+06,4.000000,3.000000,2619.500000,1.057900e+04,2.000000,2270.000000,940.000000,510.000000,320.000000,2003.000000,0.000000,47.669913,-122.116205
max,9.904000e+09,3.075000e+07,13.000000,10.500000,15360.000000,3.253932e+06,4.000000,12660.000000,8020.000000,3580.000000,4370.000000,2022.000000,2022.000000,64.824070,-70.074340

In [4]:
#display all columns 
pd.set_option('display.max_columns', None)

# Display all columns in the DataFrame
print(df)

               id        date      price  bedrooms  bathrooms  sqft_living  \
0      7399300360   5/24/2022   675000.0         4        1.0         1180
1      8910500230  12/13/2021   920000.0         5        2.5         2770
2      1180000275   9/29/2021   311000.0         6        2.0         2880
3      1604601802  12/14/2021   775000.0         3        3.0         2160
4      8562780790   8/24/2021   592500.0         2        2.0         1120
...           ...         ...        ...       ...        ...          ...
30150  7834800180  11/30/2021  1555000.0         5        2.0         1910
30151   194000695   6/16/2021  1313000.0         3        2.0         2020
30152  7960100080   5/27/2022   800000.0         3        2.0         1620
30153  2781280080   2/24/2022   775000.0         3        2.5         2570
30154  9557800100   4/29/2022   500000.0         3        1.5         1200

       sqft_lot  floors waterfront greenbelt nuisance     view condition  \
0          7140     1.0         NO        NO       NO     NONE      Good
1          6703     1.0         NO        NO      YES  AVERAGE   Average
2          6156     1.0         NO        NO       NO  AVERAGE   Average
3          1400     2.0         NO        NO       NO  AVERAGE   Average
4           758     2.0         NO        NO      YES     NONE   Average
...         ...     ...        ...       ...      ...      ...       ...
30150      4000     1.5         NO        NO       NO     NONE      Good
30151      5800     2.0         NO        NO       NO     FAIR   Average
30152      3600     1.0         NO        NO      YES     NONE   Average
30153      2889     2.0         NO        NO       NO     NONE   Average
30154     11058     1.0         NO        NO       NO     NONE   Average

           grade  heat_source sewer_system  sqft_above  sqft_basement  \
0      7 Average          Gas       PUBLIC        1180              0
1      7 Average          Oil       PUBLIC        1570           1570
2      7 Average          Gas       PUBLIC        1580           1580
3       9 Better          Gas       PUBLIC        1090           1070
4      7 Average  Electricity       PUBLIC        1120            550
...          ...          ...          ...         ...            ...
30150     8 Good          Oil       PUBLIC        1600           1130
30151  7 Average          Gas       PUBLIC        2020              0
30152  7 Average          Gas       PUBLIC         940            920
30153     8 Good          Gas       PUBLIC        1830            740
30154  7 Average          Oil       PUBLIC        1200              0

       sqft_garage  sqft_patio  yr_built  yr_renovated  \
0                0          40      1969             0
1                0         240      1950             0
2                0           0      1956             0
3              200         270      2010             0
4              550          30      2012             0
...            ...         ...       ...           ...
30150            0         210      1921             0
30151            0         520      2011             0
30152          240         110      1995             0
30153          480         100      2006             0
30154          420           0      1965             0

                                                 address        lat       long
0      2102 Southeast 21st Court, Renton, Washington ...  47.461975 -122.19052
1      11231 Greenwood Avenue North, Seattle, Washing...  47.711525 -122.35591
2      8504 South 113th Street, Seattle, Washington 9...  47.502045 -122.22520
3      4079 Letitia Avenue South, Seattle, Washington...  47.566110 -122.29020
4      2193 Northwest Talus Drive, Issaquah, Washingt...  47.532470 -122.07188
...                                                  ...        ...        ...
30150  4673 Eastern Avenue North, Seattle, Washington...  47.664740 -122.32940
30151  4131 44th Avenue Southwest, Seattle, Washingto...  47.565610 -122.38851
30152  910 Martin Luther King Jr Way, Seattle, Washin...  47.610395 -122.29585
30153  17127 114th Avenue Southeast, Renton, Washingt...  47.449490 -122.18908
30154  18615 7th Avenue South, Burien, Washington 981...  47.435840 -122.32634

[30155 rows x 25 columns]

In [5]:
# 1. Handling Missing Values
df_cleaned = df.dropna()  # Drop rows with missing values
# 2. Handling Duplicates
df_cleaned = df_cleaned.drop_duplicates()  # Remove duplicate rows

In [6]:
#display all columns and check if missing values were removed
pd.set_option('display.max_columns', None)

# Display all columns in the DataFrame
print(df_cleaned)

               id        date      price  bedrooms  bathrooms  sqft_living  \
0      7399300360   5/24/2022   675000.0         4        1.0         1180
1      8910500230  12/13/2021   920000.0         5        2.5         2770
2      1180000275   9/29/2021   311000.0         6        2.0         2880
3      1604601802  12/14/2021   775000.0         3        3.0         2160
4      8562780790   8/24/2021   592500.0         2        2.0         1120
...           ...         ...        ...       ...        ...          ...
30150  7834800180  11/30/2021  1555000.0         5        2.0         1910
30151   194000695   6/16/2021  1313000.0         3        2.0         2020
30152  7960100080   5/27/2022   800000.0         3        2.0         1620
30153  2781280080   2/24/2022   775000.0         3        2.5         2570
30154  9557800100   4/29/2022   500000.0         3        1.5         1200

       sqft_lot  floors waterfront greenbelt nuisance     view condition  \
0          7140     1.0         NO        NO       NO     NONE      Good
1          6703     1.0         NO        NO      YES  AVERAGE   Average
2          6156     1.0         NO        NO       NO  AVERAGE   Average
3          1400     2.0         NO        NO       NO  AVERAGE   Average
4           758     2.0         NO        NO      YES     NONE   Average
...         ...     ...        ...       ...      ...      ...       ...
30150      4000     1.5         NO        NO       NO     NONE      Good
30151      5800     2.0         NO        NO       NO     FAIR   Average
30152      3600     1.0         NO        NO      YES     NONE   Average
30153      2889     2.0         NO        NO       NO     NONE   Average
30154     11058     1.0         NO        NO       NO     NONE   Average

           grade  heat_source sewer_system  sqft_above  sqft_basement  \
0      7 Average          Gas       PUBLIC        1180              0
1      7 Average          Oil       PUBLIC        1570           1570
2      7 Average          Gas       PUBLIC        1580           1580
3       9 Better          Gas       PUBLIC        1090           1070
4      7 Average  Electricity       PUBLIC        1120            550
...          ...          ...          ...         ...            ...
30150     8 Good          Oil       PUBLIC        1600           1130
30151  7 Average          Gas       PUBLIC        2020              0
30152  7 Average          Gas       PUBLIC         940            920
30153     8 Good          Gas       PUBLIC        1830            740
30154  7 Average          Oil       PUBLIC        1200              0

       sqft_garage  sqft_patio  yr_built  yr_renovated  \
0                0          40      1969             0
1                0         240      1950             0
2                0           0      1956             0
3              200         270      2010             0
4              550          30      2012             0
...            ...         ...       ...           ...
30150            0         210      1921             0
30151            0         520      2011             0
30152          240         110      1995             0
30153          480         100      2006             0
30154          420           0      1965             0

                                                 address        lat       long
0      2102 Southeast 21st Court, Renton, Washington ...  47.461975 -122.19052
1      11231 Greenwood Avenue North, Seattle, Washing...  47.711525 -122.35591
2      8504 South 113th Street, Seattle, Washington 9...  47.502045 -122.22520
3      4079 Letitia Avenue South, Seattle, Washington...  47.566110 -122.29020
4      2193 Northwest Talus Drive, Issaquah, Washingt...  47.532470 -122.07188
...                                                  ...        ...        ...
30150  4673 Eastern Avenue North, Seattle, Washington...  47.664740 -122.32940
30151  4131 44th Avenue Southwest, Seattle, Washingto...  47.565610 -122.38851
30152  910 Martin Luther King Jr Way, Seattle, Washin...  47.610395 -122.29585
30153  17127 114th Avenue Southeast, Renton, Washingt...  47.449490 -122.18908
30154  18615 7th Avenue South, Burien, Washington 981...  47.435840 -122.32634

[30110 rows x 25 columns]

In [7]:
#  Encoding Categorical Variables
df_cleaned = pd.get_dummies(df_cleaned, columns=['waterfront', 'greenbelt', 'sewer_system', 'condition', 'grade', 'heat_source'])

In [9]:
#checking to see if dummie variables were encoded for categorical Variables
# 3. Encoding Categorical Variables
print(df_cleaned)

               id        date      price  bedrooms  bathrooms  sqft_living  \
0      7399300360   5/24/2022   675000.0         4        1.0         1180
1      8910500230  12/13/2021   920000.0         5        2.5         2770
2      1180000275   9/29/2021   311000.0         6        2.0         2880
3      1604601802  12/14/2021   775000.0         3        3.0         2160
4      8562780790   8/24/2021   592500.0         2        2.0         1120
...           ...         ...        ...       ...        ...          ...
30150  7834800180  11/30/2021  1555000.0         5        2.0         1910
30151   194000695   6/16/2021  1313000.0         3        2.0         2020
30152  7960100080   5/27/2022   800000.0         3        2.0         1620
30153  2781280080   2/24/2022   775000.0         3        2.5         2570
30154  9557800100   4/29/2022   500000.0         3        1.5         1200

       sqft_lot  floors nuisance     view  sqft_above  sqft_basement  \
0          7140     1.0       NO     NONE        1180              0
1          6703     1.0      YES  AVERAGE        1570           1570
2          6156     1.0       NO  AVERAGE        1580           1580
3          1400     2.0       NO  AVERAGE        1090           1070
4           758     2.0      YES     NONE        1120            550
...         ...     ...      ...      ...         ...            ...
30150      4000     1.5       NO     NONE        1600           1130
30151      5800     2.0       NO     FAIR        2020              0
30152      3600     1.0      YES     NONE         940            920
30153      2889     2.0       NO     NONE        1830            740
30154     11058     1.0       NO     NONE        1200              0

       sqft_garage  sqft_patio  yr_built  yr_renovated  \
0                0          40      1969             0
1                0         240      1950             0
2                0           0      1956             0
3              200         270      2010             0
4              550          30      2012             0
...            ...         ...       ...           ...
30150            0         210      1921             0
30151            0         520      2011             0
30152          240         110      1995             0
30153          480         100      2006             0
30154          420           0      1965             0

                                                 address        lat  \
0      2102 Southeast 21st Court, Renton, Washington ...  47.461975
1      11231 Greenwood Avenue North, Seattle, Washing...  47.711525
2      8504 South 113th Street, Seattle, Washington 9...  47.502045
3      4079 Letitia Avenue South, Seattle, Washington...  47.566110
4      2193 Northwest Talus Drive, Issaquah, Washingt...  47.532470
...                                                  ...        ...
30150  4673 Eastern Avenue North, Seattle, Washington...  47.664740
30151  4131 44th Avenue Southwest, Seattle, Washingto...  47.565610
30152  910 Martin Luther King Jr Way, Seattle, Washin...  47.610395
30153  17127 114th Avenue Southeast, Renton, Washingt...  47.449490
30154  18615 7th Avenue South, Burien, Washington 981...  47.435840

            long  waterfront_NO  waterfront_YES  greenbelt_NO  greenbelt_YES  \
0     -122.19052              1               0             1              0
1     -122.35591              1               0             1              0
2     -122.22520              1               0             1              0
3     -122.29020              1               0             1              0
4     -122.07188              1               0             1              0
...          ...            ...             ...           ...            ...
30150 -122.32940              1               0             1              0
30151 -122.38851              1               0             1              0
30152 -122.29585              1               0             1              0
30153 -122.18908              1               0             1              0
30154 -122.32634              1               0             1              0

       sewer_system_PRIVATE  sewer_system_PRIVATE RESTRICTED  \
0                         0                                0
1                         0                                0
2                         0                                0
3                         0                                0
4                         0                                0
...                     ...                              ...
30150                     0                                0
30151                     0                                0
30152                     0                                0
30153                     0                                0
30154                     0                                0

       sewer_system_PUBLIC  sewer_system_PUBLIC RESTRICTED  condition_Average  \
0                        1                               0                  0
1                        1                               0                  1
2                        1                               0                  1
3                        1                               0                  1
4                        1                               0                  1
...                    ...                             ...                ...
30150                    1                               0                  0
30151                    1                               0                  1
30152                    1                               0                  1
30153                    1                               0                  1
30154                    1                               0                  1

       condition_Fair  condition_Good  condition_Poor  condition_Very Good  \
0                   0               1               0                    0
1                   0               0               0                    0
2                   0               0               0                    0
3                   0               0               0                    0
4                   0               0               0                    0
...               ...             ...             ...                  ...
30150               0               1               0                    0
30151               0               0               0                    0
30152               0               0               0                    0
30153               0               0               0                    0
30154               0               0               0                    0

       grade_10 Very Good  grade_11 Excellent  grade_12 Luxury  \
0                       0                   0                0
1                       0                   0                0
2                       0                   0                0
3                       0                   0                0
4                       0                   0                0
...                   ...                 ...              ...
30150                   0                   0                0
30151                   0                   0                0
30152                   0                   0                0
30153                   0                   0                0
30154                   0                   0                0

       grade_13 Mansion  grade_2 Substandard  grade_3 Poor  grade_4 Low  \
0                     0                    0             0            0
1                     0                    0             0            0
2                     0                    0             0            0
3                     0                    0             0            0
4                     0                    0             0            0
...                 ...                  ...           ...          ...
30150                 0                    0             0            0
30151                 0                    0             0            0
30152                 0                    0             0            0
30153                 0                    0             0            0
30154                 0                    0             0            0

       grade_5 Fair  grade_6 Low Average  grade_7 Average  grade_8 Good  \
0                 0                    0                1             0
1                 0                    0                1             0
2                 0                    0                1             0
3                 0                    0                0             0
4                 0                    0                1             0
...             ...                  ...              ...           ...
30150             0                    0                0             1
30151             0                    0                1             0
30152             0                    0                1             0
30153             0                    0                0             1
30154             0                    0                1             0

       grade_9 Better  heat_source_Electricity  heat_source_Electricity/Solar  \
0                   0                        0                              0
1                   0                        0                              0
2                   0                        0                              0
3                   1                        0                              0
4                   0                        1                              0
...               ...                      ...                            ...
30150               0                        0                              0
30151               0                        0                              0
30152               0                        0                              0
30153               0                        0                              0
30154               0                        0                              0

       heat_source_Gas  heat_source_Gas/Solar  heat_source_Oil  \
0                    1                      0                0
1                    0                      0                1
2                    1                      0                0
3                    1                      0                0
4                    0                      0                0
...                ...                    ...              ...
30150                0                      0                1
30151                1                      0                0
30152                1                      0                0
30153                1                      0                0
30154                0                      0                1

       heat_source_Oil/Solar  heat_source_Other
0                          0                  0
1                          0                  0
2                          0                  0
3                          0                  0
4                          0                  0
...                      ...                ...
30150                      0                  0
30151                      0                  0
30152                      0                  0
30153                      0                  0
30154                      0                  0

[30110 rows x 51 columns]

In [10]:
# List of columns to remove
columns_to_remove = ['address','lat', 'long','date', 'nuisance','view', 'sqft_above', 'sqft_basement', 'sqft_garage', 'sqft_patio', 'yr_built', 'yr_renovated']

# Drop the columns from the DataFrame
df_cleaned = df_cleaned.drop(columns=columns_to_remove)

# Display the first few rows of the resulting DataFrame
print(df_cleaned.head())

           id     price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0  7399300360  675000.0         4        1.0         1180      7140     1.0
1  8910500230  920000.0         5        2.5         2770      6703     1.0
2  1180000275  311000.0         6        2.0         2880      6156     1.0
3  1604601802  775000.0         3        3.0         2160      1400     2.0
4  8562780790  592500.0         2        2.0         1120       758     2.0

   waterfront_NO  waterfront_YES  greenbelt_NO  greenbelt_YES  \
0              1               0             1              0
1              1               0             1              0
2              1               0             1              0
3              1               0             1              0
4              1               0             1              0

   sewer_system_PRIVATE  sewer_system_PRIVATE RESTRICTED  sewer_system_PUBLIC  \
0                     0                                0                    1
1                     0                                0                    1
2                     0                                0                    1
3                     0                                0                    1
4                     0                                0                    1

   sewer_system_PUBLIC RESTRICTED  condition_Average  condition_Fair  \
0                               0                  0               0
1                               0                  1               0
2                               0                  1               0
3                               0                  1               0
4                               0                  1               0

   condition_Good  condition_Poor  condition_Very Good  grade_10 Very Good  \
0               1               0                    0                   0
1               0               0                    0                   0
2               0               0                    0                   0
3               0               0                    0                   0
4               0               0                    0                   0

   grade_11 Excellent  grade_12 Luxury  grade_13 Mansion  grade_2 Substandard  \
0                   0                0                 0                    0
1                   0                0                 0                    0
2                   0                0                 0                    0
3                   0                0                 0                    0
4                   0                0                 0                    0

   grade_3 Poor  grade_4 Low  grade_5 Fair  grade_6 Low Average  \
0             0            0             0                    0
1             0            0             0                    0
2             0            0             0                    0
3             0            0             0                    0
4             0            0             0                    0

   grade_7 Average  grade_8 Good  grade_9 Better  heat_source_Electricity  \
0                1             0               0                        0
1                1             0               0                        0
2                1             0               0                        0
3                0             0               1                        0
4                1             0               0                        1

   heat_source_Electricity/Solar  heat_source_Gas  heat_source_Gas/Solar  \
0                              0                1                      0
1                              0                0                      0
2                              0                1                      0
3                              0                1                      0
4                              0                0                      0

   heat_source_Oil  heat_source_Oil/Solar  heat_source_Other
0                0                      0                  0
1                1                      0                  0
2                0                      0                  0
3                0                      0                  0
4                0                      0                  0

In [11]:
#Seperating the target variable price
housepricepreds = df_cleaned.drop('price', axis=1)
#target variable price
price_target = df_cleaned['price']
#Reviewing new rows of dataset 
housepricepreds.head()

,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront_NO,waterfront_YES,greenbelt_NO,greenbelt_YES,sewer_system_PRIVATE,sewer_system_PRIVATE RESTRICTED,sewer_system_PUBLIC,sewer_system_PUBLIC RESTRICTED,condition_Average,condition_Fair,condition_Good,condition_Poor,condition_Very Good,grade_10 Very Good,grade_11 Excellent,grade_12 Luxury,grade_13 Mansion,grade_2 Substandard,grade_3 Poor,grade_4 Low,grade_5 Fair,grade_6 Low Average,grade_7 Average,grade_8 Good,grade_9 Better,heat_source_Electricity,heat_source_Electricity/Solar,heat_source_Gas,heat_source_Gas/Solar,heat_source_Oil,heat_source_Oil/Solar,heat_source_Other
0,7399300360,4,1.0,1180,7140,1.0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0
1,8910500230,5,2.5,2770,6703,1.0,1,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
2,1180000275,6,2.0,2880,6156,1.0,1,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0
3,1604601802,3,3.0,2160,1400,2.0,1,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
4,8562780790,2,2.0,1120,758,2.0,1,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0